import { readFileSync, existsSync } from 'node:fs';
import { resolve } from 'node:path';
import assert from 'node:assert/strict';
const root = resolve('dist');
const read = path => readFileSync(resolve(root,path),'utf8');
const manifest = JSON.parse(read('manifest.webmanifest'));
assert.equal(manifest.start_url,'./');
assert.equal(manifest.scope,'./');
assert.equal(manifest.display,'standalone');
for (const icon of manifest.icons) assert.ok(existsSync(resolve(root,icon.src)), `Eksik simge: ${icon.src}`);
const sw=read('sw.js');
assert.ok(!/__(VERSION|REQUIRED|OPTIONAL|CONTENT)__/.test(sw),'Service worker üretilemedi');
const bm=JSON.parse(read('build-manifest.json'));
const precache=[...bm.required,...bm.optional.filter(e=>e!=='./')];
for(const entry of precache) assert.ok(existsSync(resolve(root,entry)), `Eksik çevrimdışı dosya: ${entry}`);
assert.ok(bm.required.includes('./index.html'),'Önbellek eksik: ./index.html');
for(const entry of ['./theme-init.js','./manifest.webmanifest']) assert.ok(bm.optional.includes(entry),`Önbellek eksik: ${entry}`);
assert.match(JSON.parse(read('app-version.json')).version,/^[a-f0-9]{12}$/);
const html=read('index.html');
for(const match of html.matchAll(/(?:src|href)="(\.\/[^"#]+)"/g)) assert.ok(existsSync(resolve(root,match[1])),`Başlangıç dosyası eksik: ${match[1]}`);
console.log(`Sürüm hazır: simgeler, başlangıç dosyaları ve ${precache.length} çevrimdışı dosya doğrulandı.`);
